ST6RI-356: Check circular membership in VTree and properly visualize memberships having unowned element
Systems-Modeling/SysML-v2-Pilot-Implementation pull request #217
Opened 2021-03-20 02:24 UTC by himi

Check circular membership in VTree.  This also fixes the problem that Model Containment validation cases were not properly visualized, which is caused by ST6RI-355.

2021-03-24 15:57 UTC, himi commented
I decided to merge this pull request with ST6RI-351 because it has many impacts to the visualization and I need fix the bugs based on the merge.

2021-03-29 06:13 UTC, seidewitz requested changes
I pulled the latest commits on branch ST6RI-356. However, trying to visualize the following package in Eclipse:
```
package Test {
	part def P {
		import P;
	}
}
```
still produces a stack overflow
```
java.lang.StackOverflowError
	at org.omg.sysml.lang.sysml.util.SysMLSwitch.doSwitch(SysMLSwitch.java:87)
	at org.eclipse.emf.ecore.util.Switch.doSwitch(Switch.java:53)
	at org.eclipse.emf.ecore.util.Switch.doSwitch(Switch.java:69)
	at org.omg.sysml.plantuml.SysML2PlantUMLText.getStereotypeStyle(SysML2PlantUMLText.java:149)
	at org.omg.sysml.plantuml.SysML2PlantUMLText.styleString(SysML2PlantUMLText.java:179)
	at org.omg.sysml.plantuml.Visitor.styleString(Visitor.java:140)
	at org.omg.sysml.plantuml.VDefault.addPUMLLine(VDefault.java:88)
	at org.omg.sysml.plantuml.VStructure.addType(VStructure.java:203)
	at org.omg.sysml.plantuml.VStructure.addType(VStructure.java:199)
	at org.omg.sysml.plantuml.VTree.addType(VTree.java:193)
	at org.omg.sysml.plantuml.VTree.caseType(VTree.java:208)
	at org.omg.sysml.plantuml.VTree.caseType(VTree.java:1)
	at org.omg.sysml.lang.sysml.util.SysMLSwitch.doSwitch(SysMLSwitch.java:784)
	at org.eclipse.emf.ecore.util.Switch.doSwitch(Switch.java:53)
	at org.eclipse.emf.ecore.util.Switch.doSwitch(Switch.java:69)
	at org.omg.sysml.plantuml.Visitor.visit(Visitor.java:400)
	at org.omg.sysml.plantuml.VTree.subtree(VTree.java:178)
	at org.omg.sysml.plantuml.VCompartment.rec(VCompartment.java:68)
	at org.omg.sysml.plantuml.VCompartment.caseMembership(VCompartment.java:287)
	at org.omg.sysml.plantuml.VTraverser.caseMembership(VTraverser.java:1)
	at org.omg.sysml.lang.sysml.util.SysMLSwitch.doSwitch(SysMLSwitch.java:130)
	at org.eclipse.emf.ecore.util.Switch.doSwitch(Switch.java:53)
	at org.eclipse.emf.ecore.util.Switch.doSwitch(Switch.java:69)
	at org.omg.sysml.plantuml.Visitor.visit(Visitor.java:400)
	at org.omg.sysml.plantuml.VTraverser.traverse(VTraverser.java:71)
	at org.omg.sysml.plantuml.VCompartment.startType(VCompartment.java:423)
	at org.omg.sysml.plantuml.VCompartment.process(VCompartment.java:431)
	at org.omg.sysml.plantuml.VTree.process(VTree.java:161)
	at org.omg.sysml.plantuml.VMixed.process(VMixed.java:41)
	at org.omg.sysml.plantuml.VTree.addType(VTree.java:195)
	at org.omg.sysml.plantuml.VTree.caseType(VTree.java:208)
	at org.omg.sysml.plantuml.VTree.caseType(VTree.java:1)
	at org.omg.sysml.lang.sysml.util.SysMLSwitch.doSwitch(SysMLSwitch.java:784)
```

2021-03-30 03:16 UTC, himi commented
Sorry. I had wrongly made that bug when solving the model containment validation case.  I fixed it and refactored the code.

2021-03-30 06:34 UTC, seidewitz approved these changes

2021-03-30 06:34 UTC, seidewitz commented
Looks good now!

2021-03-30 06:34 UTC, merged