ST6RI-532 Minor fixes to space modeling & shape library
Systems-Modeling/SysML-v2-Pilot-Implementation pull request #355
Opened 2022-04-12 13:09 UTC by conradbock

**Occurrences.kerml**

- `spaceShotOf` multiplicity: [1..] to [0..*].  Some occurrences aren't snapshots.

- invariants:
-- `innerSpaceDimension`: removed redundancy with feature type.
-- `spaceBoundaryOf`: isClosed to !isClosed
-- `spaceBoundary`: moved to after spaceBoundaryOf.
-- `SpaceShotOf`: Added that innerSpaceDimenion must be strictly lower (compare to SpaceSliceOf), not sure how it got left out.

- `spaceBoundary` description: reworded to avoid "of which".

- Typo in multiple places ("occcurrence" -> "occurrence").

**Objects.kerml**

`genus`: changed type Integer to Natural, simplified invariant.

**ShapeItems.sysml**

- Added `PlanarCurve`, to match PlanarSurface and used it below.

- Added multiplicities to quantification attributes (length, etc).

- `PlanarSurface::shape` typed by PlanarCurve.

- `Line` and `Circle` specialize PlanarCurve (moved Line after PlanarCurve/Surface).

- `Disc` specializes PlanarSurface.

- `Circle::edges::circumference`: Added "* 2".

- `Cone`: Restored radius (was being redefined), bound baseRadius to it.

- Corrected some cell multiplicities in Cone and Cuboid (along with invariant on Cone:ae).

- Added `genus = 0` to Sphere, Cone, and Cuboid.

- Removed redundant feature names when redefining as the same name.

- Moved multiplicities to just after subsetting feature names.

**CarWithShapeAndCSG.sysml**

Changed `Engine::c1` and `c2` to be cylindrically shaped, rather than specialize Cylinder, so they are bodies for intersection to each engine occurrence. The shape (space boundary) of engines is calculated by CAD tools.

2022-04-12 16:12 UTC, seidewitz requested changes
```
/**
 * A PlanarCurve is a flat Surface with a given area.
 */
item def PlanarCurve :> Curve {
	attribute :>> area [1] ;

	constraint { notEmpty(outerSpaceDimension) &  outerSpaceDimension <= 2 }
}
```
The comment doesn't seem right. A PlanarCurve is a Curve, not a Surface. Perhaps it is a cut-and-paste error.

And shouldn't the PlanarCurve have a length, not an area? An area only might make sense if the curve was closed, which isn't a requirement here.

2022-04-12 16:28 UTC, conradbock commented
Oops, copy/paste error, will fix.

2022-04-12 16:45 UTC, conradbock commented
Pushed PlanarCurve fix.  Also Objects.kerml, missed pushing it before.

2022-04-13 16:00 UTC, hpdekoning approved these changes

2022-04-13 16:01 UTC, hpdekoning commented
All looks OK for me.

2022-04-13 19:40 UTC, merged