ST6RI-565: Visualize Language Extension (PlantUML)
Systems-Modeling/SysML-v2-Pilot-Implementation pull request #385
Opened 2022-08-12 06:57 UTC by himi

Visualize language extensions.

2022-08-12 07:04 UTC, himi commented
Notice that it does not support n-ary connections.   Thus, neither n-ary derived requirements nor cause-effect is properly rendered.

2022-08-24 17:43 UTC, seidewitz requested changes
Small change: In the menu in Eclipse, "hide metadata" should be capitalized "Hide metadata", to be consistent with the other options.

2022-08-25 15:09 UTC, himi commented
Done.

2022-08-25 16:04 UTC, seidewitz approved these changes

2022-08-25 16:04 UTC, merged