ST6RI-587: Documentation is redundantly rendered as comments (PlantUML)
Systems-Modeling/SysML-v2-Pilot-Implementation pull request #412
Opened 2022-10-13 13:46 UTC by himi

Documentations in RequirementUsages were redundantly rendered in the form of comments as well as in compartments because they are a kind of comments so that the visualizer render them as comments as well.  By this fix, the visualizer render documents in compartments and if it's the case, it does not render them as comments.

2022-10-13 13:49 UTC, himi commented
```
package DocumentationTest {

part p1 {
	doc xxx /* tesafjadlfjalfjasldft */
	doc /* test2 */ 
	
	attribute aaa;
}

attribute a1 = 5 {
	doc /* attribute document */
}

requirement r1 {
	doc /* requirement documentation */
}

}
```
is rendered as:
![Screen Shot 2022-10-13 at 9 49 17 AM](https://user-images.githubusercontent.com/10537/195615133-f4eedd33-85fc-408f-9531-6f68c333ab78.png)

2022-10-13 13:50 UTC, himi commented
One remaining issue is the heading of `documentation` is not properly centred.  I'd like to improve PlantUML to support that.

2022-10-13 18:47 UTC, himi commented
Slightly changed the rendering.  Do not show a bullet if it has only one document and showed names if it has.  

![Screen Shot 2022-10-13 at 2 47 08 PM](https://user-images.githubusercontent.com/10537/195680814-abf996c6-d7f6-4a1a-b05d-084b922849e9.png)

2022-10-17 22:20 UTC, seidewitz requested changes
The rendering of multi-line comments in compartments is not very good. Documentation comments, in particular, will often be multi-line.
```
part p1 {
	doc multiline 
	/* 
	 * Documentation comments will generally have multiple lines.
	 * Like this.
	 */
	doc /* Here is another
	 * example.
	 */ 
	
	attribute aaa;
}
```
![image](https://user-images.githubusercontent.com/8561049/196294314-ebf5dc24-9084-40d9-b7d9-ac8f7553b4ea.png)
The line breaks needed to be included in the documentation text in the compartment, as they are in the textual notation. 

I also don't think the placement of the documentation name, or the use of bullets, is very natural. It would be better to just have a blank line between sequential documentation texts (a dashed or gray line separator would be even better, but not critical) and to have the name centered (to the extent possible) above the documentation text. Something like this:
```
                       multiline
Documentation comments will generally have multiple lines.
Like this.
 
Here is another
example.
```

2022-10-18 00:39 UTC, himi commented
Opps, it's my mistake on the line unfolding. How does it look to you? 

![Screen Shot 2022-10-17 at 8 36 34 PM](https://user-images.githubusercontent.com/10537/196308525-4ba449d6-dd77-45ff-91eb-db4b46ebe22e.png)

Actually, I prefer bullet style for multiple documentations to this horizontal line because it's more compact and easier to read multiple documentation items.

2022-10-19 22:21 UTC, seidewitz commented
The rendering with the line breaks looks much better. I am still not thrilled with the placement of the comment name, but I can live with it.

I like the horizontal line better than the bullets. The documentation text could include bullets itself, and I think we should have a clearer visualization for actual multiple documentation elements.

The extra lines in the example seem to come from having a line break on the last line of the documentation text. Presumably that would be the same even if bullets were used. If the final line breaks are removed, the visualization is pretty compact.
```
part p1 {
	doc multiline
	/* 
	 * Documentation comments will generally have multiple lines.
	 * Like this.*/
	doc /* Here is another
	 * example.*/ 
	
	attribute aaa;
}
```
![image](https://user-images.githubusercontent.com/8561049/196815512-7f4fd1d5-6bf2-4c23-9262-c771ade0cf2f.png)
Would it be possible to automatically remove a final new-line in documentation text before displaying text in a compartment?

2022-10-19 22:53 UTC, seidewitz commented
Another point: Shouldn't documentation have a compartment header like "attributes" and the other compartments? That would solve the problem of centering the title, and it would be more consistent. A "documentation" compartment really should just be another kind of compartment.

2022-10-20 00:53 UTC, himi commented
OK.  Let's keep the current style.  And I trimmed the body to remove heading and trailing whitespaces.  Regarding the compartment title, I would like to use always centred italic titles  for all of the compartment.  But I have no idea why PlantUML does not support that style.  I'd like to enhance PlantUML to support that.  Before that, I disabled to show a title for documentation compartment because double header lines with long documentation looks quite ugly at least for me.

2022-10-20 03:20 UTC, seidewitz commented
Clearly centered italic titles for all compartments would be better, but it seems inconsistent to try to do it for only one compartment. Especially when the title isn't actually centered.

2022-10-20 18:45 UTC, seidewitz approved these changes

2022-10-20 18:45 UTC, merged