[ST6RI-729] Do not render unnamed alias memberships
Systems-Modeling/SysML-v2-Pilot-Implementation pull request #516
Opened 2023-11-23 18:10 UTC by himi

The visualizer rendered the unnamed memberships, which are typically created by InitialNodeMember such as `first xxx;`. So it looked actions are rendered in a duplicated manner.  This PR lets the visualizer ignore such memberships.

2023-11-23 18:13 UTC, himi commented
After this fix, 
```
action a1 {
	action a11;
	first a11;
	then done;
}
```
is rendered as:
![Screenshot 2023-11-23 at 1 13 13 PM](https://github.com/Systems-Modeling/SysML-v2-Pilot-Implementation/assets/10537/99ed1791-b9f0-4f77-bca0-a08db0366be8)

2023-11-24 20:59 UTC, seidewitz requested changes
> But this rendering is not correct. The model is parsed as having a succession from `start` to `done`. There is no succession from `a11` to `done`. The proper rendering would include a symbol for `a11` and, in addition, a succession arrow from an "initial node" symbol to a "final node" symbol.

Oops, never mind, I misread the textual notation!

2023-11-24 21:07 UTC, himi commented
Sorry, I do not get what you said.  The parsed results does not have any successions involving start.  I could find only `a11` to `done`, no successions involving `a1`.
![Screenshot 2023-11-24 at 4 06 55 PM](https://github.com/Systems-Modeling/SysML-v2-Pilot-Implementation/assets/10537/480f772b-c4cd-424b-87d9-c70fb40c4911)

2023-11-24 21:13 UTC, seidewitz approved these changes

2023-11-24 21:14 UTC, merged