ST6RI-748: Standard library elements are rendered without SHOWLIB and SHOWINHERITED styles (PlantUML)
Systems-Modeling/SysML-v2-Pilot-Implementation pull request #548
Opened 2024-03-06 15:03 UTC by himi

he standard library elements are rendered even without SHOWLIB and SHOWINHERITED style if they are referred by some connectors.  Also this PR limits the maximum number of elements to be processed, which is useful for rendering with `SHOWLIB` style.

2024-03-06 15:06 UTC, himi commented
With `COMPMOST` style and in Tree view, after this fix, 
```
package TestStdLibElemInherit {
	action a1 {
		first start then a11;
		action a11;
	}
	
	action a2 {
		action a21;
	}
	
	action a3 :> a2 {
		first a21 then a31;
		action a31;
	}	
}
```
is rendered as:
![Screenshot 2024-03-06 at 10 05 04 AM](https://github.com/Systems-Modeling/SysML-v2-Pilot-Implementation/assets/10537/5d998160-8ddf-44a6-981b-ee729a64f67c)

And with `SHOWLIB` style, it is rendered as:
![Screenshot 2024-03-06 at 10 06 15 AM](https://github.com/Systems-Modeling/SysML-v2-Pilot-Implementation/assets/10537/d8bf942f-5af5-46b8-892d-be8a555eadb9)

2024-03-06 15:11 UTC, himi commented
Even with `SHOWINHERITED` style (and without `SHOWLIB`), we get the same result:
![Screenshot 2024-03-06 at 10 08 30 AM](https://github.com/Systems-Modeling/SysML-v2-Pilot-Implementation/assets/10537/3dc592a9-6b3b-4691-bfe9-dcfbd37289b0)

But with `SHOWLIB` style, it renders enormous amount of inherited elements:
![Screenshot 2024-03-06 at 10 10 02 AM](https://github.com/Systems-Modeling/SysML-v2-Pilot-Implementation/assets/10537/c55b8d65-171b-4075-a406-25805c69612d)

It takes some time to render it but due to the new limitation mechanism, it won't take so long time, it's finished in a few seconds in my Mac mini M1 environment.

2024-03-06 16:03 UTC, himi commented
Note that it is related to https://github.com/Systems-Modeling/SysML-v2-Pilot-Implementation/pull/537#issuecomment-1974914500

2024-03-16 19:01 UTC, seidewitz requested changes
I was able to reproduce all the behavior as given in previous comments. However, if action `a1` is changed to be explicitly defined by `Actions::Action` (or to explicitly subset `Action::actions`), then the library element `start` is no longer shown if SHOWLIB is true but SHOWINHERITED is false:
![image](https://github.com/Systems-Modeling/SysML-v2-Pilot-Implementation/assets/8561049/590b5aaf-921c-49b9-a9ef-d4a2a7b0372a)
It doesn't seem like the behavior of this option should depend on whether the specialization is explicit or implicit.

2024-03-16 19:19 UTC, himi commented
Hmmm... In that case, how can we tell `a1::start` does not belong to the standard library?  `ElementUtil.isStandardLibraryElement(e)` does not seem to work for that purpose.

2024-03-16 20:01 UTC, seidewitz commented
In addition, if the declaration for action `a1` is changed to
```
	action a1 {
		first a3.a31 then a11;
		action a11;
	}
```
then this is rendered as
![image](https://github.com/Systems-Modeling/SysML-v2-Pilot-Implementation/assets/8561049/dec619db-ed07-4c52-a24c-870d6ca12fe9)
While `a3` acts semantically as if it is featured by `Anything`, so it can be used as shown in `a1`, syntactically it is not actually an inherited member of `a1`, so showing it as such is not really correct.

2024-03-16 20:13 UTC, himi commented
It looks the different issue.  Again, it's related to a tricky inherit key issue.  It can be reproduced with a simpler example:
```
action a1 {
	first a3.a31 then a11;
	action a11;
}
action a3 {
	action a31;
}
```

2024-03-16 20:48 UTC, himi commented
After the investigation so far, both issues you reported are quite tricky, related to `VPath`.  And I'm now too busy to work on these.  I guess I can work on them in April.

2024-03-17 05:07 UTC, seidewitz commented
If you add these issues to the Jira backlog, then I am OK with approving this PR for the current sprint.

2024-03-18 20:26 UTC, himi commented
Thanks.  I'd like to make two Jira issues to capture these hopefully tonight.

2024-03-19 22:15 UTC, seidewitz approved these changes

2024-03-19 22:16 UTC, merged